apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc 
spec:
  replicas: 5 
  selector:
    app: nginx
  template:
    metadata:
      labels:
        name: nginx 
        app: nginx 
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

  
  ...

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
spec: 
  replicas: 5 
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - web 
  template:
    metadata:
      labels:
        name: nginx 
        app: nginx 
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80  