apiVersion: v1
kind: Pod
metadata: 
  name: secret-env-demo 
spec:
  containers:
    - name: app 
      image: nginx: 
      env:  
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username 
        - name: DB_PASS 
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: pasword
      