apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment 
spec:
  replicas: 6 
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - web 
  template:
    metadata:
      labels: 
        name: demo 
        # app: nginx 
        # env: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

      